name: '${pluginName}'
version: '${version}'
main: org.yuemi.mmomechanics.plugin.MmoMechanicsPlugin
authors: [${authors}]
contributors: [${contributors}]
api-version: '${apiVersion}'
softdepend: [
  YueMiLibs,
  PlaceholderAPI
]

commands:
  mmomechanics:
    description: Main command for MMO Mechanics
    aliases: [mmom]
    permission: mmomechanics.command
